# This is the Ansible Galaxy requirements file to pull in the correct roles
# to support the operation of CASL provisioning/runs.

# From 'tools'
- name: tools
  scm: git
  src: https://github.com/dimjost/tools
  version: master
